In [2]:
# Description: This program detects if an email is spam(1) or not spam(0)


# Import some libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string


In [3]:
# Load the data
df = pd.read_csv(r'C:\Users\Yash Kumar\Documents\emails.csv')

In [5]:
# Print the first 7 rows of dataset
df.head(7)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1

In [6]:
# Print the shaoe(No of rows and columns)
df.shape

(5728, 2)

In [7]:
# Get the columns name
df.columns

Index(['text', 'spam'], dtype='object')

In [8]:
# Check the duplicates and remove them
df.drop_duplicates(inplace = True)

In [9]:
# Show the new shapes (number of rows and column)
df.shape

(5695, 2)

In [10]:
# Show the number of missing (NAN, NaN, na) data for each columns
df.isnull().sum()

text    0
spam    0
dtype: int64

In [11]:
# Download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Yash
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [15]:
def process_text(text):
    # remove punctuation
    # remove stopwords
    # return a list of clean text words
    #1
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    #2
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    #3
    return clean_words

In [16]:
# Show the tokenization (a list of tokens also called lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [20]:
# Example
message4 = 'hello world hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()
# convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(analyzer = process_text).fit_transform([[message4], [message5]])
print(bow)
print(bow.shape)

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1
(2, 5)


In [21]:
# convert a collection of text to a metrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])

In [23]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(message_bow, df['spam'], test_size = 0.20, random_state = 0)

In [24]:
# Get the shape of messages_bow
message_bow.shape

(5695, 37229)

In [25]:
# Create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train, y_train)



In [26]:
# Print the predictions
print(classifier.predict(x_train))

[0 0 0 ... 0 0 0]


In [29]:
# Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]


In [33]:
# Evaluate the model on the training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
pred = classifier.predict(x_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print('Accuracy :', accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3445   12]
 [   1 1098]]
Accuracy : 0.9971466198419666


In [34]:
# Print the predictions
print(classifier.predict(x_test))

# Print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [35]:
# Evaluate the model on the testing dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
pred = classifier.predict(x_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print('Accuracy :', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]
Accuracy : 0.9920983318700615
